export const MUTATIONS = {
  WORKDESK: {
    CREATE_TILE: 'CREATE_TILE',
    UPDATE_TILE: 'UPDATE_TILE',
    DELETE_TILE: 'DELETE_TILE'
  },
  TRANSACTIONS: {
    CREATE_SOCKET: 'CREATE_SOCKET',
    UPDATE_LIST: 'UPDATE_TRANSACTIONS_LIST',
    RESET_LIST: 'RESET_TRANSACTIONS_LIST',
    MARK_SOCKET_INITIALIZED: 'MARK_SOCKET_INITIALIZED',
    SET_SOCKET_ERROR: 'SET_SOCKET_ERROR',
    CLEAR_DATA: 'CLEAR_DATA',
    TOGGLE_CONNECT_STATUS: 'TOGGLE_CONNECT_STATUS'
  }
};

export const ACTIONS = {
  WORKDESK: {
    GENERATE_TILE: 'GENERATE_TILE',
    CHANGE_TILE: 'CHANGE_TILE',
    REMOVE_TILE: 'REMOVE_TILE',
    SAVE_TO_STORAGE: 'SAVE_TO_STORAGE'
  },
  TRANSACTIONS: {
    INIT_SOCKET: 'INIT_SOCKET',
    CHECK_SOCKET: 'CHECK_SOCKET',
    CONNECT_TO_SOCKET: 'CONNECT_TO_SOCKET',
    DISCONNECT_FROM_SOCKET: 'DISCONNECT_FROM_SOCKET'
  }
};
