export const MUTATIONS = {
  WORKDESK: {
    GENERATE_TILE: 'GENERATE_TILE',
    CHANGE_TILE_DATA: 'CHANGE_TILE_DATA',
    REMOVE_TILE: 'REMOVE_TILE'
  },
  TRANSACTIONS: {
    CREATE_SOCKET: 'CREATE_SOCKET',
    UPDATE_LIST: 'UPDATE_TRANSACTIONS_LIST',
    RESET_LIST: 'RESET_TRANSACTIONS_LIST',
    MARK_SOCKET_INITIALIZED: 'MARK_SOCKET_INITIALIZED',
    SET_SOCKET_ERROR: 'SET_SOCKET_ERROR',
    CLEAR_DATA: 'CLEAR_DATA',
    TOGGLE_CONNECT_STATUS: 'TOGGLE_CONNECT_STATUS'
  }
};

export const ACTIONS = {
  TRANSACTIONS: {
    INIT_SOCKET: 'INIT_SOCKET',
    CHECK_SOCKET: 'CHECK_SOCKET',
    CONNECT_TO_SOCKET: 'CONNECT_TO_SOCKET',
    DISCONNECT_FROM_SOCKET: 'DISCONNECT_FROM_SOCKET'
  }
};
